<?php
/**
 * KatSkillLookupDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Prosoft\RecruitingApi\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * prosoftrecruiting API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.3
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
namespace Prosoft\RecruitingApi\Api\Dto;

use ArrayAccess;
use Prosoft\RecruitingApi\Api\ObjectSerializer;

/**
 * KatSkillLookupDto Class Doc Comment
 *
 * @category    Class
 * @description Erweitert das Prosoft.Tenant.Dto.LookupDto um die Prosoft.Tenant.Shared.Enums.SkillArt und die Gruppe.
 * @package     Prosoft\RecruitingApi\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KatSkillLookupDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'KatSkillLookupDto';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'art'          => 'int',
        'grp_uuid'     => 'string',
        'skill_source' => 'int',
        'bezeichnung'  => 'string',
        'object_uuid'  => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'art'          => 'int32',
        'grp_uuid'     => 'uuid',
        'skill_source' => 'int32',
        'bezeichnung'  => null,
        'object_uuid'  => 'uuid',
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'art'          => 'Art',
        'grp_uuid'     => 'GrpUuid',
        'skill_source' => 'SkillSource',
        'bezeichnung'  => 'Bezeichnung',
        'object_uuid'  => 'ObjectUuid',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'art'          => 'setArt',
        'grp_uuid'     => 'setGrpUuid',
        'skill_source' => 'setSkillSource',
        'bezeichnung'  => 'setBezeichnung',
        'object_uuid'  => 'setObjectUuid',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'art'          => 'getArt',
        'grp_uuid'     => 'getGrpUuid',
        'skill_source' => 'getSkillSource',
        'bezeichnung'  => 'getBezeichnung',
        'object_uuid'  => 'getObjectUuid',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const ART_1 = 1;
    const ART_2 = 2;
    const SKILL_SOURCE_1 = 1;
    const SKILL_SOURCE_2 = 2;
    const SKILL_SOURCE_3 = 3;
    const SKILL_SOURCE_4 = 4;
    const SKILL_SOURCE_5 = 5;

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getArtAllowableValues()
    {
        return [
            self::ART_1,
            self::ART_2,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSkillSourceAllowableValues()
    {
        return [
            self::SKILL_SOURCE_1,
            self::SKILL_SOURCE_2,
            self::SKILL_SOURCE_3,
            self::SKILL_SOURCE_4,
            self::SKILL_SOURCE_5,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['art'] = isset($data['art']) ? $data['art'] : null;
        $this->container['grp_uuid'] = isset($data['grp_uuid']) ? $data['grp_uuid'] : null;
        $this->container['skill_source'] = isset($data['skill_source']) ? $data['skill_source'] : null;
        $this->container['bezeichnung'] = isset($data['bezeichnung']) ? $data['bezeichnung'] : null;
        $this->container['object_uuid'] = isset($data['object_uuid']) ? $data['object_uuid'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getArtAllowableValues();
        if (!in_array($this->container['art'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'art', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSkillSourceAllowableValues();
        if (!in_array($this->container['skill_source'], $allowedValues)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'skill_source', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        $allowedValues = $this->getArtAllowableValues();
        if (!in_array($this->container['art'], $allowedValues)) {
            return false;
        }
        $allowedValues = $this->getSkillSourceAllowableValues();
        if (!in_array($this->container['skill_source'], $allowedValues)) {
            return false;
        }
        return true;
    }

    /**
     * Gets art
     *
     * @return int
     */
    public function getArt()
    {
        return $this->container['art'];
    }

    /**
     * Sets art
     *
     * @param int $art Holt oder setzt die Skill-Art.
     *
     * @return $this
     */
    public function setArt($art)
    {
        $allowedValues = $this->getArtAllowableValues();
        if (!is_null($art) && !in_array($art, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'art', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['art'] = $art;

        return $this;
    }

    /**
     * Gets grp_uuid
     *
     * @return string
     */
    public function getGrpUuid()
    {
        return $this->container['grp_uuid'];
    }

    /**
     * Sets grp_uuid
     *
     * @param string $grp_uuid Holt oder setzt die Uuid der Skillgruppe
     *
     * @return $this
     */
    public function setGrpUuid($grp_uuid)
    {
        $this->container['grp_uuid'] = $grp_uuid;

        return $this;
    }

    /**
     * Gets skill_source
     *
     * @return int
     */
    public function getSkillSource()
    {
        return $this->container['skill_source'];
    }

    /**
     * Sets skill_source
     *
     * @param int $skill_source Holt oder setzt die Prosoft.Tenant.Shared.Enums.SkillQuelle
     *
     * @return $this
     */
    public function setSkillSource($skill_source)
    {
        $allowedValues = $this->getSkillSourceAllowableValues();
        if (!is_null($skill_source) && !in_array($skill_source, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'skill_source', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['skill_source'] = $skill_source;

        return $this;
    }

    /**
     * Gets bezeichnung
     *
     * @return string
     */
    public function getBezeichnung()
    {
        return $this->container['bezeichnung'];
    }

    /**
     * Sets bezeichnung
     *
     * @param string $bezeichnung Die Bezeichnung des Eintrags.
     *
     * @return $this
     */
    public function setBezeichnung($bezeichnung)
    {
        $this->container['bezeichnung'] = $bezeichnung;

        return $this;
    }

    /**
     * Gets object_uuid
     *
     * @return string
     */
    public function getObjectUuid()
    {
        return $this->container['object_uuid'];
    }

    /**
     * Sets object_uuid
     *
     * @param string $object_uuid Die Object-Uuid
     *
     * @return $this
     */
    public function setObjectUuid($object_uuid)
    {
        $this->container['object_uuid'] = $object_uuid;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int   $offset Offset
     * @param mixed $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
