<?php
/**
 * MitarbeiterDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Prosoft\RecruitingApi\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * prosoftrecruiting API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.3
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
namespace Prosoft\RecruitingApi\Api\Dto;

use ArrayAccess;
use Prosoft\RecruitingApi\Api\ObjectSerializer;

/**
 * MitarbeiterDto Class Doc Comment
 *
 * @category    Class
 * @description Die Daten des Mitarbeiters
 * @package     Prosoft\RecruitingApi\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MitarbeiterDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $swaggerModelName = 'MitarbeiterDto';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerTypes = [
        'adresse_hausnummer'       => 'string',
        'adresse_land'             => '\Prosoft\RecruitingApi\Api\Dto\LookupDto',
        'adresse_ort'              => 'string',
        'adresse_plz'              => 'string',
        'adresse_strasse'          => 'string',
        'anrede'                   => '\Prosoft\RecruitingApi\Api\Dto\LookupDto',
        'arbeitserlaubnis_bis'     => '\DateTime',
        'aufenthaltserlaubnis_bis' => '\DateTime',
        'bevorzugter_kanal'        => '\Prosoft\RecruitingApi\Api\Dto\LookupDto',
        'email'                    => 'string',
        'familienstand'            => '\Prosoft\RecruitingApi\Api\Dto\LookupDto',
        'fax'                      => 'string',
        'geburtsdatum'             => '\DateTime',
        'geburtsname'              => 'string',
        'geburtsort'               => 'string',
        'mobil'                    => 'string',
        'nachname'                 => 'string',
        'namensvorsatz'            => 'string',
        'namenszusatz'             => 'string',
        'nationalitaet'            => '\Prosoft\RecruitingApi\Api\Dto\LookupDto',
        'telefon'                  => 'string',
        'titel'                    => '\Prosoft\RecruitingApi\Api\Dto\LookupDto',
        'url_facebook'             => 'string',
        'url_google_plus'          => 'string',
        'url_linked_in'            => 'string',
        'url_twitter'              => 'string',
        'url_xing'                 => 'string',
        'vorname'                  => 'string',
        'webseite'                 => 'string',
        'weitere_vornamen'         => 'string',
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $swaggerFormats = [
        'adresse_hausnummer'       => null,
        'adresse_land'             => null,
        'adresse_ort'              => null,
        'adresse_plz'              => null,
        'adresse_strasse'          => null,
        'anrede'                   => null,
        'arbeitserlaubnis_bis'     => 'date-time',
        'aufenthaltserlaubnis_bis' => 'date-time',
        'bevorzugter_kanal'        => null,
        'email'                    => null,
        'familienstand'            => null,
        'fax'                      => null,
        'geburtsdatum'             => 'date-time',
        'geburtsname'              => null,
        'geburtsort'               => null,
        'mobil'                    => null,
        'nachname'                 => null,
        'namensvorsatz'            => null,
        'namenszusatz'             => null,
        'nationalitaet'            => null,
        'telefon'                  => null,
        'titel'                    => null,
        'url_facebook'             => null,
        'url_google_plus'          => null,
        'url_linked_in'            => null,
        'url_twitter'              => null,
        'url_xing'                 => null,
        'vorname'                  => null,
        'webseite'                 => null,
        'weitere_vornamen'         => null,
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'adresse_hausnummer'       => 'AdresseHausnummer',
        'adresse_land'             => 'AdresseLand',
        'adresse_ort'              => 'AdresseOrt',
        'adresse_plz'              => 'AdressePlz',
        'adresse_strasse'          => 'AdresseStrasse',
        'anrede'                   => 'Anrede',
        'arbeitserlaubnis_bis'     => 'ArbeitserlaubnisBis',
        'aufenthaltserlaubnis_bis' => 'AufenthaltserlaubnisBis',
        'bevorzugter_kanal'        => 'BevorzugterKanal',
        'email'                    => 'Email',
        'familienstand'            => 'Familienstand',
        'fax'                      => 'Fax',
        'geburtsdatum'             => 'Geburtsdatum',
        'geburtsname'              => 'Geburtsname',
        'geburtsort'               => 'Geburtsort',
        'mobil'                    => 'Mobil',
        'nachname'                 => 'Nachname',
        'namensvorsatz'            => 'Namensvorsatz',
        'namenszusatz'             => 'Namenszusatz',
        'nationalitaet'            => 'Nationalitaet',
        'telefon'                  => 'Telefon',
        'titel'                    => 'Titel',
        'url_facebook'             => 'UrlFacebook',
        'url_google_plus'          => 'UrlGooglePlus',
        'url_linked_in'            => 'UrlLinkedIn',
        'url_twitter'              => 'UrlTwitter',
        'url_xing'                 => 'UrlXing',
        'vorname'                  => 'Vorname',
        'webseite'                 => 'Webseite',
        'weitere_vornamen'         => 'WeitereVornamen',
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'adresse_hausnummer'       => 'setAdresseHausnummer',
        'adresse_land'             => 'setAdresseLand',
        'adresse_ort'              => 'setAdresseOrt',
        'adresse_plz'              => 'setAdressePlz',
        'adresse_strasse'          => 'setAdresseStrasse',
        'anrede'                   => 'setAnrede',
        'arbeitserlaubnis_bis'     => 'setArbeitserlaubnisBis',
        'aufenthaltserlaubnis_bis' => 'setAufenthaltserlaubnisBis',
        'bevorzugter_kanal'        => 'setBevorzugterKanal',
        'email'                    => 'setEmail',
        'familienstand'            => 'setFamilienstand',
        'fax'                      => 'setFax',
        'geburtsdatum'             => 'setGeburtsdatum',
        'geburtsname'              => 'setGeburtsname',
        'geburtsort'               => 'setGeburtsort',
        'mobil'                    => 'setMobil',
        'nachname'                 => 'setNachname',
        'namensvorsatz'            => 'setNamensvorsatz',
        'namenszusatz'             => 'setNamenszusatz',
        'nationalitaet'            => 'setNationalitaet',
        'telefon'                  => 'setTelefon',
        'titel'                    => 'setTitel',
        'url_facebook'             => 'setUrlFacebook',
        'url_google_plus'          => 'setUrlGooglePlus',
        'url_linked_in'            => 'setUrlLinkedIn',
        'url_twitter'              => 'setUrlTwitter',
        'url_xing'                 => 'setUrlXing',
        'vorname'                  => 'setVorname',
        'webseite'                 => 'setWebseite',
        'weitere_vornamen'         => 'setWeitereVornamen',
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'adresse_hausnummer'       => 'getAdresseHausnummer',
        'adresse_land'             => 'getAdresseLand',
        'adresse_ort'              => 'getAdresseOrt',
        'adresse_plz'              => 'getAdressePlz',
        'adresse_strasse'          => 'getAdresseStrasse',
        'anrede'                   => 'getAnrede',
        'arbeitserlaubnis_bis'     => 'getArbeitserlaubnisBis',
        'aufenthaltserlaubnis_bis' => 'getAufenthaltserlaubnisBis',
        'bevorzugter_kanal'        => 'getBevorzugterKanal',
        'email'                    => 'getEmail',
        'familienstand'            => 'getFamilienstand',
        'fax'                      => 'getFax',
        'geburtsdatum'             => 'getGeburtsdatum',
        'geburtsname'              => 'getGeburtsname',
        'geburtsort'               => 'getGeburtsort',
        'mobil'                    => 'getMobil',
        'nachname'                 => 'getNachname',
        'namensvorsatz'            => 'getNamensvorsatz',
        'namenszusatz'             => 'getNamenszusatz',
        'nationalitaet'            => 'getNationalitaet',
        'telefon'                  => 'getTelefon',
        'titel'                    => 'getTitel',
        'url_facebook'             => 'getUrlFacebook',
        'url_google_plus'          => 'getUrlGooglePlus',
        'url_linked_in'            => 'getUrlLinkedIn',
        'url_twitter'              => 'getUrlTwitter',
        'url_xing'                 => 'getUrlXing',
        'vorname'                  => 'getVorname',
        'webseite'                 => 'getWebseite',
        'weitere_vornamen'         => 'getWeitereVornamen',
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['adresse_hausnummer'] = isset($data['adresse_hausnummer']) ? $data['adresse_hausnummer'] : null;
        $this->container['adresse_land'] = isset($data['adresse_land']) ? $data['adresse_land'] : null;
        $this->container['adresse_ort'] = isset($data['adresse_ort']) ? $data['adresse_ort'] : null;
        $this->container['adresse_plz'] = isset($data['adresse_plz']) ? $data['adresse_plz'] : null;
        $this->container['adresse_strasse'] = isset($data['adresse_strasse']) ? $data['adresse_strasse'] : null;
        $this->container['anrede'] = isset($data['anrede']) ? $data['anrede'] : null;
        $this->container['arbeitserlaubnis_bis'] = isset($data['arbeitserlaubnis_bis']) ? $data['arbeitserlaubnis_bis'] : null;
        $this->container['aufenthaltserlaubnis_bis'] = isset($data['aufenthaltserlaubnis_bis']) ? $data['aufenthaltserlaubnis_bis'] : null;
        $this->container['bevorzugter_kanal'] = isset($data['bevorzugter_kanal']) ? $data['bevorzugter_kanal'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['familienstand'] = isset($data['familienstand']) ? $data['familienstand'] : null;
        $this->container['fax'] = isset($data['fax']) ? $data['fax'] : null;
        $this->container['geburtsdatum'] = isset($data['geburtsdatum']) ? $data['geburtsdatum'] : null;
        $this->container['geburtsname'] = isset($data['geburtsname']) ? $data['geburtsname'] : null;
        $this->container['geburtsort'] = isset($data['geburtsort']) ? $data['geburtsort'] : null;
        $this->container['mobil'] = isset($data['mobil']) ? $data['mobil'] : null;
        $this->container['nachname'] = isset($data['nachname']) ? $data['nachname'] : null;
        $this->container['namensvorsatz'] = isset($data['namensvorsatz']) ? $data['namensvorsatz'] : null;
        $this->container['namenszusatz'] = isset($data['namenszusatz']) ? $data['namenszusatz'] : null;
        $this->container['nationalitaet'] = isset($data['nationalitaet']) ? $data['nationalitaet'] : null;
        $this->container['telefon'] = isset($data['telefon']) ? $data['telefon'] : null;
        $this->container['titel'] = isset($data['titel']) ? $data['titel'] : null;
        $this->container['url_facebook'] = isset($data['url_facebook']) ? $data['url_facebook'] : null;
        $this->container['url_google_plus'] = isset($data['url_google_plus']) ? $data['url_google_plus'] : null;
        $this->container['url_linked_in'] = isset($data['url_linked_in']) ? $data['url_linked_in'] : null;
        $this->container['url_twitter'] = isset($data['url_twitter']) ? $data['url_twitter'] : null;
        $this->container['url_xing'] = isset($data['url_xing']) ? $data['url_xing'] : null;
        $this->container['vorname'] = isset($data['vorname']) ? $data['vorname'] : null;
        $this->container['webseite'] = isset($data['webseite']) ? $data['webseite'] : null;
        $this->container['weitere_vornamen'] = isset($data['weitere_vornamen']) ? $data['weitere_vornamen'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['anrede'] === null) {
            $invalidProperties[] = "'anrede' can't be null";
        }
        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        if ($this->container['nachname'] === null) {
            $invalidProperties[] = "'nachname' can't be null";
        }
        if ($this->container['vorname'] === null) {
            $invalidProperties[] = "'vorname' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        if ($this->container['anrede'] === null) {
            return false;
        }
        if ($this->container['email'] === null) {
            return false;
        }
        if ($this->container['nachname'] === null) {
            return false;
        }
        if ($this->container['vorname'] === null) {
            return false;
        }
        return true;
    }

    /**
     * Gets adresse_hausnummer
     *
     * @return string
     */
    public function getAdresseHausnummer()
    {
        return $this->container['adresse_hausnummer'];
    }

    /**
     * Sets adresse_hausnummer
     *
     * @param string $adresse_hausnummer Die Hausnummer
     *
     * @return $this
     */
    public function setAdresseHausnummer($adresse_hausnummer)
    {
        $this->container['adresse_hausnummer'] = $adresse_hausnummer;

        return $this;
    }

    /**
     * Gets adresse_land
     *
     * @return \Prosoft\RecruitingApi\Api\Dto\LookupDto
     */
    public function getAdresseLand()
    {
        return $this->container['adresse_land'];
    }

    /**
     * Sets adresse_land
     *
     * @param \Prosoft\RecruitingApi\Api\Dto\LookupDto $adresse_land adresse_land
     *
     * @return $this
     */
    public function setAdresseLand($adresse_land)
    {
        $this->container['adresse_land'] = $adresse_land;

        return $this;
    }

    /**
     * Gets adresse_ort
     *
     * @return string
     */
    public function getAdresseOrt()
    {
        return $this->container['adresse_ort'];
    }

    /**
     * Sets adresse_ort
     *
     * @param string $adresse_ort Der Ort
     *
     * @return $this
     */
    public function setAdresseOrt($adresse_ort)
    {
        $this->container['adresse_ort'] = $adresse_ort;

        return $this;
    }

    /**
     * Gets adresse_plz
     *
     * @return string
     */
    public function getAdressePlz()
    {
        return $this->container['adresse_plz'];
    }

    /**
     * Sets adresse_plz
     *
     * @param string $adresse_plz Die PLZ
     *
     * @return $this
     */
    public function setAdressePlz($adresse_plz)
    {
        $this->container['adresse_plz'] = $adresse_plz;

        return $this;
    }

    /**
     * Gets adresse_strasse
     *
     * @return string
     */
    public function getAdresseStrasse()
    {
        return $this->container['adresse_strasse'];
    }

    /**
     * Sets adresse_strasse
     *
     * @param string $adresse_strasse Die Straße
     *
     * @return $this
     */
    public function setAdresseStrasse($adresse_strasse)
    {
        $this->container['adresse_strasse'] = $adresse_strasse;

        return $this;
    }

    /**
     * Gets anrede
     *
     * @return \Prosoft\RecruitingApi\Api\Dto\LookupDto
     */
    public function getAnrede()
    {
        return $this->container['anrede'];
    }

    /**
     * Sets anrede
     *
     * @param \Prosoft\RecruitingApi\Api\Dto\LookupDto $anrede anrede
     *
     * @return $this
     */
    public function setAnrede($anrede)
    {
        $this->container['anrede'] = $anrede;

        return $this;
    }

    /**
     * Gets arbeitserlaubnis_bis
     *
     * @return \DateTime
     */
    public function getArbeitserlaubnisBis()
    {
        return $this->container['arbeitserlaubnis_bis'];
    }

    /**
     * Sets arbeitserlaubnis_bis
     *
     * @param \DateTime $arbeitserlaubnis_bis Das Datum wann die Arbeitserlaubnis endet
     *
     * @return $this
     */
    public function setArbeitserlaubnisBis($arbeitserlaubnis_bis)
    {
        $this->container['arbeitserlaubnis_bis'] = $arbeitserlaubnis_bis;

        return $this;
    }

    /**
     * Gets aufenthaltserlaubnis_bis
     *
     * @return \DateTime
     */
    public function getAufenthaltserlaubnisBis()
    {
        return $this->container['aufenthaltserlaubnis_bis'];
    }

    /**
     * Sets aufenthaltserlaubnis_bis
     *
     * @param \DateTime $aufenthaltserlaubnis_bis Das Datum wann die Aufenthaltserlaubnis endet
     *
     * @return $this
     */
    public function setAufenthaltserlaubnisBis($aufenthaltserlaubnis_bis)
    {
        $this->container['aufenthaltserlaubnis_bis'] = $aufenthaltserlaubnis_bis;

        return $this;
    }

    /**
     * Gets bevorzugter_kanal
     *
     * @return \Prosoft\RecruitingApi\Api\Dto\LookupDto
     */
    public function getBevorzugterKanal()
    {
        return $this->container['bevorzugter_kanal'];
    }

    /**
     * Sets bevorzugter_kanal
     *
     * @param \Prosoft\RecruitingApi\Api\Dto\LookupDto $bevorzugter_kanal bevorzugter_kanal
     *
     * @return $this
     */
    public function setBevorzugterKanal($bevorzugter_kanal)
    {
        $this->container['bevorzugter_kanal'] = $bevorzugter_kanal;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email Die E-Mail-Adresse
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets familienstand
     *
     * @return \Prosoft\RecruitingApi\Api\Dto\LookupDto
     */
    public function getFamilienstand()
    {
        return $this->container['familienstand'];
    }

    /**
     * Sets familienstand
     *
     * @param \Prosoft\RecruitingApi\Api\Dto\LookupDto $familienstand familienstand
     *
     * @return $this
     */
    public function setFamilienstand($familienstand)
    {
        $this->container['familienstand'] = $familienstand;

        return $this;
    }

    /**
     * Gets fax
     *
     * @return string
     */
    public function getFax()
    {
        return $this->container['fax'];
    }

    /**
     * Sets fax
     *
     * @param string $fax Die FAX-Nummer
     *
     * @return $this
     */
    public function setFax($fax)
    {
        $this->container['fax'] = $fax;

        return $this;
    }

    /**
     * Gets geburtsdatum
     *
     * @return \DateTime
     */
    public function getGeburtsdatum()
    {
        return $this->container['geburtsdatum'];
    }

    /**
     * Sets geburtsdatum
     *
     * @param \DateTime $geburtsdatum Das Geburtsdatum
     *
     * @return $this
     */
    public function setGeburtsdatum($geburtsdatum)
    {
        $this->container['geburtsdatum'] = $geburtsdatum;

        return $this;
    }

    /**
     * Gets geburtsname
     *
     * @return string
     */
    public function getGeburtsname()
    {
        return $this->container['geburtsname'];
    }

    /**
     * Sets geburtsname
     *
     * @param string $geburtsname Der Geburtsname
     *
     * @return $this
     */
    public function setGeburtsname($geburtsname)
    {
        $this->container['geburtsname'] = $geburtsname;

        return $this;
    }

    /**
     * Gets geburtsort
     *
     * @return string
     */
    public function getGeburtsort()
    {
        return $this->container['geburtsort'];
    }

    /**
     * Sets geburtsort
     *
     * @param string $geburtsort Der Geburtsort
     *
     * @return $this
     */
    public function setGeburtsort($geburtsort)
    {
        $this->container['geburtsort'] = $geburtsort;

        return $this;
    }

    /**
     * Gets mobil
     *
     * @return string
     */
    public function getMobil()
    {
        return $this->container['mobil'];
    }

    /**
     * Sets mobil
     *
     * @param string $mobil Die Mobilfunknummer
     *
     * @return $this
     */
    public function setMobil($mobil)
    {
        $this->container['mobil'] = $mobil;

        return $this;
    }

    /**
     * Gets nachname
     *
     * @return string
     */
    public function getNachname()
    {
        return $this->container['nachname'];
    }

    /**
     * Sets nachname
     *
     * @param string $nachname Der Nachname
     *
     * @return $this
     */
    public function setNachname($nachname)
    {
        $this->container['nachname'] = $nachname;

        return $this;
    }

    /**
     * Gets namensvorsatz
     *
     * @return string
     */
    public function getNamensvorsatz()
    {
        return $this->container['namensvorsatz'];
    }

    /**
     * Sets namensvorsatz
     *
     * @param string $namensvorsatz Der Namensvorsatz
     *
     * @return $this
     */
    public function setNamensvorsatz($namensvorsatz)
    {
        $this->container['namensvorsatz'] = $namensvorsatz;

        return $this;
    }

    /**
     * Gets namenszusatz
     *
     * @return string
     */
    public function getNamenszusatz()
    {
        return $this->container['namenszusatz'];
    }

    /**
     * Sets namenszusatz
     *
     * @param string $namenszusatz Der Namenszusatz
     *
     * @return $this
     */
    public function setNamenszusatz($namenszusatz)
    {
        $this->container['namenszusatz'] = $namenszusatz;

        return $this;
    }

    /**
     * Gets nationalitaet
     *
     * @return \Prosoft\RecruitingApi\Api\Dto\LookupDto
     */
    public function getNationalitaet()
    {
        return $this->container['nationalitaet'];
    }

    /**
     * Sets nationalitaet
     *
     * @param \Prosoft\RecruitingApi\Api\Dto\LookupDto $nationalitaet nationalitaet
     *
     * @return $this
     */
    public function setNationalitaet($nationalitaet)
    {
        $this->container['nationalitaet'] = $nationalitaet;

        return $this;
    }

    /**
     * Gets telefon
     *
     * @return string
     */
    public function getTelefon()
    {
        return $this->container['telefon'];
    }

    /**
     * Sets telefon
     *
     * @param string $telefon Die Telefonnummer
     *
     * @return $this
     */
    public function setTelefon($telefon)
    {
        $this->container['telefon'] = $telefon;

        return $this;
    }

    /**
     * Gets titel
     *
     * @return \Prosoft\RecruitingApi\Api\Dto\LookupDto
     */
    public function getTitel()
    {
        return $this->container['titel'];
    }

    /**
     * Sets titel
     *
     * @param \Prosoft\RecruitingApi\Api\Dto\LookupDto $titel titel
     *
     * @return $this
     */
    public function setTitel($titel)
    {
        $this->container['titel'] = $titel;

        return $this;
    }

    /**
     * Gets url_facebook
     *
     * @return string
     */
    public function getUrlFacebook()
    {
        return $this->container['url_facebook'];
    }

    /**
     * Sets url_facebook
     *
     * @param string $url_facebook Die Facebook-URL
     *
     * @return $this
     */
    public function setUrlFacebook($url_facebook)
    {
        $this->container['url_facebook'] = $url_facebook;

        return $this;
    }

    /**
     * Gets url_google_plus
     *
     * @return string
     */
    public function getUrlGooglePlus()
    {
        return $this->container['url_google_plus'];
    }

    /**
     * Sets url_google_plus
     *
     * @param string $url_google_plus Die GooglePlus-URL
     *
     * @return $this
     */
    public function setUrlGooglePlus($url_google_plus)
    {
        $this->container['url_google_plus'] = $url_google_plus;

        return $this;
    }

    /**
     * Gets url_linked_in
     *
     * @return string
     */
    public function getUrlLinkedIn()
    {
        return $this->container['url_linked_in'];
    }

    /**
     * Sets url_linked_in
     *
     * @param string $url_linked_in Die LinkedIn-URL
     *
     * @return $this
     */
    public function setUrlLinkedIn($url_linked_in)
    {
        $this->container['url_linked_in'] = $url_linked_in;

        return $this;
    }

    /**
     * Gets url_twitter
     *
     * @return string
     */
    public function getUrlTwitter()
    {
        return $this->container['url_twitter'];
    }

    /**
     * Sets url_twitter
     *
     * @param string $url_twitter Die Twitter-URL
     *
     * @return $this
     */
    public function setUrlTwitter($url_twitter)
    {
        $this->container['url_twitter'] = $url_twitter;

        return $this;
    }

    /**
     * Gets url_xing
     *
     * @return string
     */
    public function getUrlXing()
    {
        return $this->container['url_xing'];
    }

    /**
     * Sets url_xing
     *
     * @param string $url_xing Die XING-URL
     *
     * @return $this
     */
    public function setUrlXing($url_xing)
    {
        $this->container['url_xing'] = $url_xing;

        return $this;
    }

    /**
     * Gets vorname
     *
     * @return string
     */
    public function getVorname()
    {
        return $this->container['vorname'];
    }

    /**
     * Sets vorname
     *
     * @param string $vorname Der Vorname
     *
     * @return $this
     */
    public function setVorname($vorname)
    {
        $this->container['vorname'] = $vorname;

        return $this;
    }

    /**
     * Gets webseite
     *
     * @return string
     */
    public function getWebseite()
    {
        return $this->container['webseite'];
    }

    /**
     * Sets webseite
     *
     * @param string $webseite Die URL zur Website
     *
     * @return $this
     */
    public function setWebseite($webseite)
    {
        $this->container['webseite'] = $webseite;

        return $this;
    }

    /**
     * Gets weitere_vornamen
     *
     * @return string
     */
    public function getWeitereVornamen()
    {
        return $this->container['weitere_vornamen'];
    }

    /**
     * Sets weitere_vornamen
     *
     * @param string $weitere_vornamen Weitere Vornamen
     *
     * @return $this
     */
    public function setWeitereVornamen($weitere_vornamen)
    {
        $this->container['weitere_vornamen'] = $weitere_vornamen;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param int $offset Offset
     *
     * @return bool
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param int $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int   $offset Offset
     * @param mixed $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param int $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
